### ISSUE TITLE
Update for repl.it possible?

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/console_ip_whitelist#11]
I seem to have gotten better_errors to work on repl.it:

https://repl.it/@raghubetina/test-better-errors

Note lines 37 and 38 of application.rb.

It seems to be stable, at least after about an hour.

Perhaps it's possible to get better_errors working on repl.it after all? What was the issue you were running into, specifically, @jelaniwoods?

**Comment by jelaniwoods** [comment]
@raghubetina  I was having an issue with the `ip_whitelist` gem because the [ip of the repl would change](https://github.com/firstdraft/appdev/issues/86#issuecomment-488421275), so even if I whitelisted an ip, I was still locked out of the better errors page.

**Comment by raghubetina** [comment]
@jelaniwoods The IP of the repl itself changing shouldn't be an issue; as long as the IP of the _visitor_ is stable (i.e., as long as REPL.it isn't doing some weird internal routing that makes the visitor's IP look different to the server on every visit).

Perhaps the `whitelist.yml` file was not being read in correctly on repl.it? Notice that I put the IP directly into `application.rb`; the gem is supposed to read the YAML file and do the `BetterErrors::Middleware.allow_ip!` for each IP address (and also [similarly for `web-console`](https://github.com/rails/web-console#configweb_consolepermissions)).

**Comment by raghubetina** [comment]
I think this is where I originally started:

https://stackoverflow.com/questions/27117443/why-doesnt-better-errors-work-on-cloud-9-ide/41633349#41633349
