### ISSUE TITLE
SRP gitignoring in grade_runner and whitelist

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/console_ip_whitelist#2]
Students modify both grades.yml (when they add their token) and whitelist.yml (when they add IPs).

We are currently adding both files and then adding them to gitignore.

However when you modify a file that has been tracked, the changes are **not ignored**. The wind up in the diff. This exposes sensitive info when the commit, causes confusing info to show up in web_git changes view, and causes unnecessary git conflicts on group projects.

 - [x] `grades.yml` should always be ignored. There's no need to track it at all. We need to stop tracking it initially. (Update appdev_template if necessary.)

 - [x] `whitelist.yml` contains some information, a default set of IPs, that does need to come with the project. This should be renamed to `default_whitelist.yml`.

 - [x] Another file should be created when `bin/whitelist` is run called `whitelist.yml`. This file should be always gitignored (update appdev_template if necessary).

**Comment by arjunvenkat** [comment]
Will renaming of `whitelist` to `default_whitelist` cause any issues with the `console_ip_whitelist` gem? Or are they independent of each other?

**Comment by raghubetina** [comment]
The gem will need to be updated to use both, I think.
